from __future__ import annotations

import mimetypes
import shutil
from datetime import datetime, timezone
from email.utils import format_datetime
from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path
from xml.etree.ElementTree import Element, SubElement, tostring

from kindle2mp3.sessions import Session, SessionManager


def _audio_info(session: Session) -> tuple[Path, str, str] | None:
    """Return (path, mime_type, extension) for the session's output audio, or None."""
    output = session.metadata.get("output", {})
    if not isinstance(output, dict):
        return None
    audio_path_str = output.get("audio_path")
    if not audio_path_str:
        return None
    audio_path = Path(audio_path_str)
    if not audio_path.exists():
        return None
    ext = audio_path.suffix.lower()
    mime = {"mp3": "audio/mpeg", "m4a": "audio/mp4", "wav": "audio/wav"}.get(
        ext.lstrip("."), "application/octet-stream"
    )
    return audio_path, mime, ext


def generate_feed(
    *,
    manager: SessionManager,
    output_dir: Path,
    base_url: str,
    title: str = "kindle2mp3",
    description: str = "Audiobooks generated by kindle2mp3",
) -> tuple[Path, int]:
    """Generate a podcast RSS feed XML and copy audio files into output_dir.

    Returns (feed_path, episode_count).
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    media_dir = output_dir / "media"
    media_dir.mkdir(exist_ok=True)

    sessions = manager.list_sessions()
    episodes: list[tuple[Session, Path, str, str]] = []
    for s in sessions:
        if s.metadata.get("status") != "merge_completed":
            continue
        info = _audio_info(s)
        if info is None:
            continue
        episodes.append((s, *info))

    base_url = base_url.rstrip("/")

    rss = Element("rss", version="2.0", attrib={
        "xmlns:itunes": "http://www.itunes.com/dtds/podcast-1.0.dtd",
    })
    channel = SubElement(rss, "channel")
    SubElement(channel, "title").text = title
    SubElement(channel, "description").text = description
    SubElement(channel, "link").text = base_url
    SubElement(channel, "language").text = "ja"
    SubElement(channel, "generator").text = "kindle2mp3"

    for session, audio_path, mime, ext in episodes:
        dest_name = f"{session.session_id}{ext}"
        dest_path = media_dir / dest_name
        if not dest_path.exists() or dest_path.stat().st_mtime < audio_path.stat().st_mtime:
            shutil.copy2(audio_path, dest_path)

        ep_title = session.metadata.get("title") or session.session_id
        created = session.metadata.get("created_at", "")
        try:
            pub_date = datetime.fromisoformat(created)
        except (ValueError, TypeError):
            pub_date = datetime.now(timezone.utc)

        file_size = dest_path.stat().st_size
        enclosure_url = f"{base_url}/media/{dest_name}"

        item = SubElement(channel, "item")
        SubElement(item, "title").text = ep_title
        SubElement(item, "pubDate").text = format_datetime(pub_date)
        SubElement(item, "enclosure", url=enclosure_url, length=str(file_size), type=mime)
        SubElement(item, "guid", isPermaLink="false").text = session.session_id
        desc_parts = []
        capture = session.metadata.get("capture", {})
        if isinstance(capture, dict) and capture.get("page_count"):
            desc_parts.append(f"Pages: {capture['page_count']}")
        tts = session.metadata.get("tts", {})
        if isinstance(tts, dict) and tts.get("chunk_count"):
            desc_parts.append(f"Chunks: {tts['chunk_count']}")
        SubElement(item, "description").text = ", ".join(desc_parts) or ep_title

    feed_path = output_dir / "feed.xml"
    xml_bytes = b'<?xml version="1.0" encoding="UTF-8"?>\n' + tostring(rss, encoding="unicode").encode("utf-8")
    feed_path.write_bytes(xml_bytes)
    return feed_path, len(episodes)


class PodcastRequestHandler(SimpleHTTPRequestHandler):
    def log_message(self, format, *args):
        print(f"[podcast] {self.address_string()} - {format % args}", flush=True)


def serve(*, directory: Path, host: str, port: int) -> None:
    """Serve the podcast feed directory over HTTP."""

    class Handler(PodcastRequestHandler):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, directory=str(directory), **kwargs)

    server = HTTPServer((host, port), Handler)
    print(f"Serving podcast at http://{host}:{port}/", flush=True)
    print(f"Feed URL: http://{host}:{port}/feed.xml", flush=True)
    print("Press Ctrl+C to stop.", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopped.", flush=True)
        server.server_close()
